ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_VELOCITY_INCREASE = 1.2

CIRCLESHAPE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOT_SPEED = 500
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300

SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280
SHOT_RADIOUS = 5